spring:
  profiles:
    actives:
    - dev 
---
server:
  port: 8001         
spring:
  profiles: dev     #开发环境
  application:
    name: MicroServiceCloud-Config-Dept-Client
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: oracle.jdbc.driver.OracleDriver      # oracle驱动包
    url: jdbc:oracle:thin:@localhost:1521:orcl              # 数据库名称
    username: jxrisk
    password: jxrisk
    dbcp2:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200                                  # 等待连接获取的最大超时时间
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml        # mybatis配置文件所在路径
  type-aliases-package: com.yss.Entity    # 所有Entity别名类所在包
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml                       # mapper映射文件
  
    
eureka:
  client:                           #客户端注册金服务列表
    server-url: 
      defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance: 
    instance-id: dept-8001.com
    prefer-ip-address: true
    
info:                                                      #主要是点击超链接的时候，不在出现error页面，显示每个服务的详细信息
 
  app.name: microservicecloud
  company.name: www.yss.com
  build.artifactId: ${project.artifactId}
  build.version: ${project.version}
  
---

server:
  port: 8001        #注册中心占用7001端口，冒号后面必须有空格  
spring:
  profiles: test     #测试环境
  application:
    name: MicroServiceCloud-Config-Dept-Client
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: oracle.jdbc.driver.OracleDriver      # oracle驱动包
    url: jdbc:oracle:thin:@localhost:1521:orcl              # 数据库名称
    username: jxrisk
    password: jxrisk
    dbcp2:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200                                  # 等待连接获取的最大超时时间
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml        # mybatis配置文件所在路径
  type-aliases-package: com.yss.Entity    # 所有Entity别名类所在包
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml                       # mapper映射文件
  
    
eureka:
  client:                           #客户端注册金服务列表
    server-url: 
      defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance: 
    instance-id: dept-8001.com
    prefer-ip-address: true
    
info:                                                      # 主要是点击超链接的时候，不在出现error页面，显示每个服务的详细信息
  app.name: microservicecloud
  company.name: www.yss.com
  build.artifactId: ${project.artifactId}
  build.version: ${project.version}

    
#每次修改的时候切记保存为UTF-8，要不然上传到GitHub会乱码