spring: 
  profiles: 
    actives: 
    - dev 
---
server: 
  port: 7001

spring: 
  profiles: dev     #开发环境
  application: 
    name: MicroServiceCloud-Config-Erueka-Client
    
eureka:                                   #关闭eureka自动保护功能(server:enable-self-preservation: false)
  instance: 
    hostname: eureka7001.com              #eureka服务端的实例名称
  client: 
    register-with-eureka: false           #false表示不向注册中心注册自己。
    fetch-registry: false                 #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    service-url: 
      defaultZone: http://eureka7001.com:7001/eureka/        #设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址      
---
server: 
  port: 7001         #注册中心占用7001端口，冒号后面必须有空格
  
spring: 
  profiles: test     #测试环境
  application:
    name: MicroServiceCloud-Config-Erueka-Client
    
eureka:                                   #关闭eureka自动保护功能(server:enable-self-preservation: false)
  instance: 
    hostname: eureka7001.com              #eureka服务端的实例名称
  client: 
    register-with-eureka: false           #false表示不向注册中心注册自己。
    fetch-registry: false                 #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    service-url: 
      defaultZone: http://eureka7001.com:7001/eureka/        #设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址

    
#每次修改的时候切记保存为UTF-8，要不然上传到GitHub会乱码