spring:
  profiles:
    actives:
    - dev 
---

server:
  port: 7001        #注册中心占用7001端口，冒号后面必须有空格
  
  
spring:
  profiles: dev     #开发环境
  application:
    name: MicroServiceCloud-Config-Erueka-Client
    
    
eureka:
  instance:
    hostname: eureka7001.com
  client:
    register-with-eureka: false     #当前的eureka自己不注册到注册中心
    fetch-registry: false           #不通过eureka获取注册中心
    server-url: 
      defaultZone: http://eureka-7001.com:7001/eureka/
      
---
server:
  port: 7001        #注册中心占用7001端口，冒号后面必须有空格
  
spring:
  profiles: test     #测试环境
  application:
    name: MicroServiceCloud-Config-Erueka-Client
    
    
eureka:
  instance:
    hostname: eureka7001.com
  client:
    register-with-eureka: false     #当前的eureka自己不注册到注册中心
    fetch-registry: false           #不通过eureka获取注册中心
    server-url: 
      defaultZone: http://eureka-7001.com:7001/eureka/

    
#每次修改的时候切记保存为UTF-8，要不然上传到GitHub会乱码